export const GET_ABILITIES_CONFIG = 'GET_ABILITIES_CONFIG';
export const SET_ABILITIES_CONFIG = 'SET_ABILITIES_CONFIG';
export const SET_ABILITIES = 'SET_ABILITIES';
export const SET_LOADING = 'SET_LOADING';
